### ISSUE TITLE
support click and multi selection

### ISSUE THREAD

**Issue by allenlongbaobao** [stephan281094/vue-drag-select#11]
hi, i viewed your library and learned a lot. Would you plan to add click item to select and multi select when use enter ctrl or command ? i overwrite your code and do that on my way. the demo is here: [demo](https://www.allenwang.top/Selection) 
If you are interested in this, i hope i can pull request to your code.
best wishes.

**Comment by stephan281094** [comment]
This is now part of `0.2.0`. You can use `shift` to expand your selection!
