### ISSUE TITLE
selectedItems should be the array of vue components when the child elements are vue components

### ISSUE THREAD

**Issue by FrancisKong** [stephan281094/vue-drag-select#3]
My code has broken after I uprade 0.1.2 to 0.1.3, because the `selectedItems` is a `HTMLCollection` instead of the array of vue components, and I can't use the component property or method.

**Comment by stephan281094** [comment]
Thanks again for contributing! Updating to 0.1.4 should fix the problem.

**Comment by FrancisKong** [comment]
It works now, thanks!
