### ISSUE TITLE
Compiled version of library to use without Vue loader

### ISSUE THREAD

**Issue by Grawl** [stephan281094/vue-drag-select#5]
Today I'm working on a project that used compiled Vue without Webpack, just plain 'ol JS.

So I have to modify your lib to bootstrap my prototype.

**Comment by stephan281094** [comment]
Hi there! That's definitely on the roadmap. It'd be great to have a prebuilt version of `vue-drag-select` in a `dist` folder, so it can be used without a bundler like Webpack.

PRs are welcome!

**Comment by Grawl** [comment]
Good!

**Comment by Grawl** [comment]
as a workaround, I use it [like this gist](https://gist.github.com/Grawl/25885cabfb31d88f39549de1d331762e#file-vue-drag-select-js-L101)

**Comment by liquidvisual** [comment]
Is this no longer happening?
