### ISSUE TITLE
when page scrolled, the selectionBox will out of the selection

### ISSUE THREAD

**Issue by kunnet** [stephan281094/vue-drag-select#7]
![issue](https://user-images.githubusercontent.com/8035485/33640484-eb242a64-da6b-11e7-8f62-853a726c4771.gif)

**Comment by stephan281094** [comment]
Hi @kunnet, nice catch! A fix has been submitted by @FrancisKong in #8. Once this pull request gets merged, we'll be releasing a new version containing the fix.

**Comment by niksy** [comment]
@stephan281094 any chance of getting this merged? Version from @FrancisKong already has a lot fixes and improvements that can be applied to main repository.

**Comment by stephan281094** [comment]
@niksy The pull request has been merged and a release has been made. Thanks for the heads-up!
